// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/alpha.dart';
import '../engine/planner.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `conn`, `db_path`, `de`, `import_legacy_json`, `ser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 初始化：迁移旧 JSON（若存在）。
Future<void> init() => RustLib.instance.api.crateApiHistoryStoreInit();

/// 读取全部记录（按 id 升序）。
Future<List<Rec>> load() => RustLib.instance.api.crateApiHistoryStoreLoad();

/// 全量保存（单事务）。
Future<void> save({required List<Rec> recs}) =>
    RustLib.instance.api.crateApiHistoryStoreSave(recs: recs);

/// 一条任务历史记录（与 TaskEntry/TaskDto 字段对应）。
class Rec {
  final BigInt id;
  final String source;
  final String output;
  final int tileSize;
  final Scheme scheme;
  final AlphaMode alpha;
  final Resample resample;
  final int? zmin;
  final int? zmax;

  /// 全透明瓦片跳过写入
  final bool skipEmpty;

  /// GDAL mercator 绝对级别模式
  final bool mercator;
  final String status;
  final int level;
  final BigInt tilesDone;
  final BigInt totalTiles;
  final BigInt bytesWritten;
  final BigInt elapsedMs;
  final String? error;
  final BigInt startedMs;
  final BigInt finishedMs;

  /// 瓦片边界（JSON：scheme/tile/zmin/zmax/levels[{z,ox,oy,tx,ty,wy}]）
  final String? boundsJson;

  const Rec({
    required this.id,
    required this.source,
    required this.output,
    required this.tileSize,
    required this.scheme,
    required this.alpha,
    required this.resample,
    this.zmin,
    this.zmax,
    required this.skipEmpty,
    required this.mercator,
    required this.status,
    required this.level,
    required this.tilesDone,
    required this.totalTiles,
    required this.bytesWritten,
    required this.elapsedMs,
    this.error,
    required this.startedMs,
    required this.finishedMs,
    this.boundsJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      output.hashCode ^
      tileSize.hashCode ^
      scheme.hashCode ^
      alpha.hashCode ^
      resample.hashCode ^
      zmin.hashCode ^
      zmax.hashCode ^
      skipEmpty.hashCode ^
      mercator.hashCode ^
      status.hashCode ^
      level.hashCode ^
      tilesDone.hashCode ^
      totalTiles.hashCode ^
      bytesWritten.hashCode ^
      elapsedMs.hashCode ^
      error.hashCode ^
      startedMs.hashCode ^
      finishedMs.hashCode ^
      boundsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rec &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          output == other.output &&
          tileSize == other.tileSize &&
          scheme == other.scheme &&
          alpha == other.alpha &&
          resample == other.resample &&
          zmin == other.zmin &&
          zmax == other.zmax &&
          skipEmpty == other.skipEmpty &&
          mercator == other.mercator &&
          status == other.status &&
          level == other.level &&
          tilesDone == other.tilesDone &&
          totalTiles == other.totalTiles &&
          bytesWritten == other.bytesWritten &&
          elapsedMs == other.elapsedMs &&
          error == other.error &&
          startedMs == other.startedMs &&
          finishedMs == other.finishedMs &&
          boundsJson == other.boundsJson;
}
