// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_type`, `handle`, `respond`, `servers`, `url_decode`

/// 为目录启动（或复用）静态服务，返回端口。
/// 服务随进程生命周期存活；重复调用同一目录返回既有端口。
Future<int> previewServe({required String dir}) =>
    RustLib.instance.api.crateApiPreviewServerPreviewServe(dir: dir);
