// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/alpha.dart';
import '../engine/planner.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'task_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `acquire`, `broadcast`, `default_concurrency`, `is_terminal`, `load_history`, `log`, `manager`, `new`, `now_ms`, `persist`, `release`, `to_dto`, `worker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Gate`, `Manager`, `SlotGuard`, `Snap`, `TaskEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ImageBrief> readImageInfo({required String path}) =>
    RustLib.instance.api.crateApiTaskApiReadImageInfo(path: path);

/// 按给定参数估算各级瓦片数（UI 滑块实时调用，纯计算无 IO）。
/// mercator=true 时走 GDAL 绝对级别语义（需要地理参考）。
Future<PyramidEstimate> estimatePyramidEx({
  required String source,
  required int width,
  required int height,
  required int tileSize,
  int? zmin,
  int? zmax,
  required bool mercator,
}) => RustLib.instance.api.crateApiTaskApiEstimatePyramidEx(
  source: source,
  width: width,
  height: height,
  tileSize: tileSize,
  zmin: zmin,
  zmax: zmax,
  mercator: mercator,
);

/// 兼容旧接口：相对模式估算。
Future<List<LevelEstimate>> estimatePyramid({
  required int width,
  required int height,
  required int tileSize,
  int? zmin,
  int? zmax,
}) => RustLib.instance.api.crateApiTaskApiEstimatePyramid(
  width: width,
  height: height,
  tileSize: tileSize,
  zmin: zmin,
  zmax: zmax,
);

/// 生成界面内预览缩略图（PNG 字节）。超大图按行带抽稀采样，内存有界。
/// 采样源图指定坐标的 RGBA 像素值（供预览点选取色）。
Future<Uint8List> samplePixel({
  required String source,
  required PlatformInt64 x,
  required PlatformInt64 y,
}) =>
    RustLib.instance.api.crateApiTaskApiSamplePixel(source: source, x: x, y: y);

Future<Uint8List> makePreview({required String source, required int maxPx}) =>
    RustLib.instance.api.crateApiTaskApiMakePreview(
      source: source,
      maxPx: maxPx,
    );

Stream<TaskEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiTaskApiSubscribeEvents();

Future<BigInt> startTask({required TaskConfig cfg}) =>
    RustLib.instance.api.crateApiTaskApiStartTask(cfg: cfg);

Future<bool> cancelTask({required BigInt id}) =>
    RustLib.instance.api.crateApiTaskApiCancelTask(id: id);

/// 暂停：引擎工作线程在下一块瓦片前停靠。
Future<bool> pauseTask({required BigInt id}) =>
    RustLib.instance.api.crateApiTaskApiPauseTask(id: id);

/// 恢复已暂停的任务。
Future<bool> resumeTask({required BigInt id}) =>
    RustLib.instance.api.crateApiTaskApiResumeTask(id: id);

Future<bool> removeTask({required BigInt id}) =>
    RustLib.instance.api.crateApiTaskApiRemoveTask(id: id);

Future<void> setMaxConcurrency({required int n}) =>
    RustLib.instance.api.crateApiTaskApiSetMaxConcurrency(n: n);

Future<int> getMaxConcurrency() =>
    RustLib.instance.api.crateApiTaskApiGetMaxConcurrency();

Future<List<TaskDto>> listTasks() =>
    RustLib.instance.api.crateApiTaskApiListTasks();

/// 图像元信息 + 默认金字塔估算。
class ImageBrief {
  final int width;
  final int height;
  final String pixelFormat;
  final String compression;
  final String chunkType;
  final Uint32List chunkHint;
  final bool hasAlpha;
  final BigInt rgbaBytes;
  final int maxLevel;

  const ImageBrief({
    required this.width,
    required this.height,
    required this.pixelFormat,
    required this.compression,
    required this.chunkType,
    required this.chunkHint,
    required this.hasAlpha,
    required this.rgbaBytes,
    required this.maxLevel,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      pixelFormat.hashCode ^
      compression.hashCode ^
      chunkType.hashCode ^
      chunkHint.hashCode ^
      hasAlpha.hashCode ^
      rgbaBytes.hashCode ^
      maxLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageBrief &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixelFormat == other.pixelFormat &&
          compression == other.compression &&
          chunkType == other.chunkType &&
          chunkHint == other.chunkHint &&
          hasAlpha == other.hasAlpha &&
          rgbaBytes == other.rgbaBytes &&
          maxLevel == other.maxLevel;
}

/// 单级别瓦片估算。
class LevelEstimate {
  final int level;
  final int width;
  final int height;
  final int tilesX;
  final int tilesY;
  final BigInt tiles;

  const LevelEstimate({
    required this.level,
    required this.width,
    required this.height,
    required this.tilesX,
    required this.tilesY,
    required this.tiles,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      width.hashCode ^
      height.hashCode ^
      tilesX.hashCode ^
      tilesY.hashCode ^
      tiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LevelEstimate &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          width == other.width &&
          height == other.height &&
          tilesX == other.tilesX &&
          tilesY == other.tilesY &&
          tiles == other.tiles;
}

/// 金字塔估算结果（双模式）。
class PyramidEstimate {
  /// mercator 模式下为 GSD 对应 native zoom；relative 模式 None
  final int? nativeZoom;
  final List<LevelEstimate> levels;

  const PyramidEstimate({this.nativeZoom, required this.levels});

  @override
  int get hashCode => nativeZoom.hashCode ^ levels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PyramidEstimate &&
          runtimeType == other.runtimeType &&
          nativeZoom == other.nativeZoom &&
          levels == other.levels;
}

/// 一个切片任务的全部配置（Dart 侧构造）。
class TaskConfig {
  final String source;
  final String output;
  final int tileSize;
  final int? zmin;
  final int? zmax;
  final Scheme scheme;
  final AlphaMode alpha;
  final Resample resample;

  /// 全透明瓦片跳过写入
  final bool skipEmpty;

  /// true = GDAL mercator 绝对级别模式（要求 GeoTIFF）
  final bool mercator;

  /// 预览页底图/叠加层（JSON 数组字符串；None=空）
  final String? previewOverlays;

  const TaskConfig({
    required this.source,
    required this.output,
    required this.tileSize,
    this.zmin,
    this.zmax,
    required this.scheme,
    required this.alpha,
    required this.resample,
    required this.skipEmpty,
    required this.mercator,
    this.previewOverlays,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      output.hashCode ^
      tileSize.hashCode ^
      zmin.hashCode ^
      zmax.hashCode ^
      scheme.hashCode ^
      alpha.hashCode ^
      resample.hashCode ^
      skipEmpty.hashCode ^
      mercator.hashCode ^
      previewOverlays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskConfig &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          output == other.output &&
          tileSize == other.tileSize &&
          zmin == other.zmin &&
          zmax == other.zmax &&
          scheme == other.scheme &&
          alpha == other.alpha &&
          resample == other.resample &&
          skipEmpty == other.skipEmpty &&
          mercator == other.mercator &&
          previewOverlays == other.previewOverlays;
}

/// 任务列表条目快照。
class TaskDto {
  final BigInt id;
  final String source;
  final String output;
  final int tileSize;
  final Scheme scheme;
  final AlphaMode alpha;
  final Resample resample;
  final int? zmin;
  final int? zmax;
  final String status;
  final int level;
  final BigInt tilesDone;
  final BigInt totalTiles;
  final BigInt bytesWritten;
  final BigInt elapsedMs;
  final String? error;

  /// 开始 / 完成时刻（Unix 毫秒；0 表示未知）
  final BigInt startedAtMs;
  final BigInt finishedAtMs;

  const TaskDto({
    required this.id,
    required this.source,
    required this.output,
    required this.tileSize,
    required this.scheme,
    required this.alpha,
    required this.resample,
    this.zmin,
    this.zmax,
    required this.status,
    required this.level,
    required this.tilesDone,
    required this.totalTiles,
    required this.bytesWritten,
    required this.elapsedMs,
    this.error,
    required this.startedAtMs,
    required this.finishedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      output.hashCode ^
      tileSize.hashCode ^
      scheme.hashCode ^
      alpha.hashCode ^
      resample.hashCode ^
      zmin.hashCode ^
      zmax.hashCode ^
      status.hashCode ^
      level.hashCode ^
      tilesDone.hashCode ^
      totalTiles.hashCode ^
      bytesWritten.hashCode ^
      elapsedMs.hashCode ^
      error.hashCode ^
      startedAtMs.hashCode ^
      finishedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          output == other.output &&
          tileSize == other.tileSize &&
          scheme == other.scheme &&
          alpha == other.alpha &&
          resample == other.resample &&
          zmin == other.zmin &&
          zmax == other.zmax &&
          status == other.status &&
          level == other.level &&
          tilesDone == other.tilesDone &&
          totalTiles == other.totalTiles &&
          bytesWritten == other.bytesWritten &&
          elapsedMs == other.elapsedMs &&
          error == other.error &&
          startedAtMs == other.startedAtMs &&
          finishedAtMs == other.finishedAtMs;
}

class TaskEvent {
  final BigInt taskId;
  final TaskEventKind kind;

  const TaskEvent({required this.taskId, required this.kind});

  @override
  int get hashCode => taskId.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskEvent &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          kind == other.kind;
}

@freezed
sealed class TaskEventKind with _$TaskEventKind {
  const TaskEventKind._();

  const factory TaskEventKind.statusChanged({required String status}) =
      TaskEventKind_StatusChanged;
  const factory TaskEventKind.started({required BigInt totalTiles}) =
      TaskEventKind_Started;
  const factory TaskEventKind.levelStart({required int level}) =
      TaskEventKind_LevelStart;
  const factory TaskEventKind.progress({
    required int level,
    required BigInt tilesDone,
    required BigInt totalTiles,
    required BigInt bytesWritten,
    required BigInt elapsedMs,
  }) = TaskEventKind_Progress;
  const factory TaskEventKind.finished({required TaskSummary summary}) =
      TaskEventKind_Finished;
}

class TaskSummary {
  final BigInt tilesDone;
  final BigInt totalTiles;
  final BigInt bytesWritten;
  final BigInt elapsedMs;
  final bool cancelled;
  final String? error;

  const TaskSummary({
    required this.tilesDone,
    required this.totalTiles,
    required this.bytesWritten,
    required this.elapsedMs,
    required this.cancelled,
    this.error,
  });

  @override
  int get hashCode =>
      tilesDone.hashCode ^
      totalTiles.hashCode ^
      bytesWritten.hashCode ^
      elapsedMs.hashCode ^
      cancelled.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskSummary &&
          runtimeType == other.runtimeType &&
          tilesDone == other.tilesDone &&
          totalTiles == other.totalTiles &&
          bytesWritten == other.bytesWritten &&
          elapsedMs == other.elapsedMs &&
          cancelled == other.cancelled &&
          error == other.error;
}
