// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'alpha.freezed.dart';

@freezed
sealed class AlphaMode with _$AlphaMode {
  const AlphaMode._();

  /// 保留源 Alpha
  const factory AlphaMode.keep() = AlphaMode_Keep;

  /// Alpha 阈值：a < below → 全透明
  const factory AlphaMode.threshold({required int below}) = AlphaMode_Threshold;

  /// 颜色键：接近指定颜色的像素置透明
  const factory AlphaMode.colorKey({
    required int r,
    required int g,
    required int b,
    required int tolerance,
  }) = AlphaMode_ColorKey;
}
